// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"pam/greet/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

// 请求接口路径入口
func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet, // 接口请求方法
				Path:    "/greet",
				Handler: GreetHandler(serverCtx), //接口信息处理
			},
			{
				Method:  http.MethodGet,
				Path:    "/bye",
				Handler: ByeHandle(serverCtx),
			},
		},
	)
}
