// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	//Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type ByeResponse struct {
	Message string            `json:"message"`
	Code    string            `json:"code"`
	Data    map[string]string `json:"data"`
}
